// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.579Z
// // =============================================
//
// import { Item } from '../schema/item.schema.ts';
// import { ItemEntity } from '../entity/item.entity';
//
// export class ItemMapper {
//   public static toModel(entity: ItemEntity): Item {
//     const model = new Item();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.image = ?; // TODO: Manual mapping
//     // model.description = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.ItemModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Item): ItemEntity {
//     return new ItemEntity({
//       // Common fields
//       // Entity-only fields (manual mapping required)
//       // name: undefined, // TODO: Manual mapping
//       // partNo: undefined, // TODO: Manual mapping
//       // materialNo: undefined, // TODO: Manual mapping
//       // type: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: Item[]): ItemEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: ItemEntity[]): Item[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
