// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.579Z
// // =============================================
//
// import { ItemType } from '../schema/item-type.schema.ts';
// import { ItemTypeEntity } from '../entity/item-type.entity';
//
// export class ItemTypeMapper {
//   public static toModel(entity: ItemTypeEntity): ItemType {
//     const model = new ItemType();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.ItemTypeModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: ItemType): ItemTypeEntity {
//     return new ItemTypeEntity({
//       // Common fields
//       // Entity-only fields (manual mapping required)
//       // type: undefined, // TODO: Manual mapping
//       // description: undefined, // TODO: Manual mapping
//       // isIssue: undefined, // TODO: Manual mapping
//       // isReturn: undefined, // TODO: Manual mapping
//       // isReplenish: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: ItemType[]): ItemTypeEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: ItemTypeEntity[]): ItemType[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
