// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.579Z
// // =============================================
//
// import { Log } from '../schema/log.schema.ts';
// import { LogEntity } from '../entity/log.entity';
//
// export class LogMapper {
//   public static toModel(entity: LogEntity): Log {
//     const model = new Log();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.method = ?; // TODO: Manual mapping
//     // model.url = ?; // TODO: Manual mapping
//     // model.userAgent = ?; // TODO: Manual mapping
//     // model.clientIp = ?; // TODO: Manual mapping
//     // model.referenceNo = ?; // TODO: Manual mapping
//     // model.request = ?; // TODO: Manual mapping
//     // model.response = ?; // TODO: Manual mapping
//     // model.statusCode = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.LogModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Log): LogEntity {
//     return new LogEntity({
//       // Common fields
//     });
//   }
//
//   public static toEntities(models: Log[]): LogEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: LogEntity[]): Log[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
