// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.579Z
// // =============================================
//
// import { NotificationSetting } from '../schema/notification-setting.schema.ts';
// import { NotificationSettingEntity } from '../entity/notification-setting.entity';
//
// export class NotificationSettingMapper {
//   public static toModel(entity: NotificationSettingEntity): NotificationSetting {
//     const model = new NotificationSetting();
//
//     // Common fields
//     model.type = entity.type;
//     model.type = entity.type;
//     model.type = entity.type;
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.required = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.NotificationSettingModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: NotificationSetting): NotificationSettingEntity {
//     return new NotificationSettingEntity({
//       // Common fields
//       type: model.type,
//       type: model.type,
//       type: model.type,
//
//       // Entity-only fields (manual mapping required)
//       // time: undefined, // TODO: Manual mapping
//       // startTime: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: NotificationSetting[]): NotificationSettingEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: NotificationSettingEntity[]): NotificationSetting[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
