// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.583Z
// // =============================================
//
// import { Reader } from '../schema/reader.schema.ts';
// import { ReaderEntity } from '../entity/reader.entity';
//
// export class ReaderMapper {
//   public static toModel(entity: ReaderEntity): Reader {
//     const model = new Reader();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.currentUser = ?; // TODO: Manual mapping
//     // model.default = ?; // TODO: Manual mapping
//     // model.default = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.ReaderModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Reader): ReaderEntity {
//     return new ReaderEntity({
//       // Common fields
//       // Entity-only fields (manual mapping required)
//       // code: undefined, // TODO: Manual mapping
//       // isConfirm: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: Reader[]): ReaderEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: ReaderEntity[]): Reader[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
