// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.583Z
// // =============================================
//
// import { Room } from '../schema/room.schema.ts';
// import { RoomEntity } from '../entity/room.entity';
//
// export class RoomMapper {
//   public static toModel(entity: RoomEntity): Room {
//     const model = new Room();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.description = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.RoomModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Room): RoomEntity {
//     return new RoomEntity({
//       // Common fields
//       // Entity-only fields (manual mapping required)
//       // name: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: Room[]): RoomEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: RoomEntity[]): Room[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
