// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.583Z
// // =============================================
//
// import { Router } from '../schema/router.schema.ts';
// import { RouterEntity } from '../entity/router.entity';
//
// export class RouterMapper {
//   public static toModel(entity: RouterEntity): Router {
//     const model = new Router();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.RouterModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Router): RouterEntity {
//     return new RouterEntity({
//       // Common fields
//       // Entity-only fields (manual mapping required)
//       // number: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: Router[]): RouterEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: RouterEntity[]): Router[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
