// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.584Z
// // =============================================
//
// import { Shelf } from '../schema/shelf.schema.ts';
// import { ShelfEntity } from '../entity/shelf.entity';
//
// export class ShelfMapper {
//   public static toModel(entity: ShelfEntity): Shelf {
//     const model = new Shelf();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.required = ?; // TODO: Manual mapping
//     // model.infor = ?; // TODO: Manual mapping
//     // model.hardWarePort = ?; // TODO: Manual mapping
//     // model.nucId = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.lockerPort = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.ShelfModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Shelf): ShelfEntity {
//     return new ShelfEntity({
//       // Common fields
//       // Entity-only fields (manual mapping required)
//       // name: undefined, // TODO: Manual mapping
//     });
//   }
//
//   public static toEntities(models: Shelf[]): ShelfEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: ShelfEntity[]): Shelf[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
