// // =============================================
// // 🚨 AUTO-GENERATED FILE - DO NOT EDIT! 🚨
// // Generated by: generate-mappers.ts
// // Date: 2025-07-16T16:30:51.584Z
// // =============================================
//
// import { Transaction } from '../schema/transaction.schema.ts';
// import { TransactionEntity } from '../entity/transaction.entity';
//
// export class TransactionMapper {
//   public static toModel(entity: TransactionEntity): Transaction {
//     const model = new Transaction();
//
//     // Common fields
//
//     // Schema-only fields (manual mapping required)
//     // model.name = ?; // TODO: Manual mapping
//     // model.status = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.clusterId = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.requestQty = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.isSync = ?; // TODO: Manual mapping
//     // model.default = ?; // TODO: Manual mapping
//     // model.type = ?; // TODO: Manual mapping
//     // model.mid = ?; // TODO: Manual mapping
//     // model.timestamps = ?; // TODO: Manual mapping
//     // model.TransactionModel = ?; // TODO: Manual mapping
//
//     return model;
//   }
//
//   public static toEntity(model: Transaction): TransactionEntity {
//     return new TransactionEntity({
//       // Common fields
//     });
//   }
//
//   public static toEntities(models: Transaction[]): TransactionEntity[] {
//     return models.map((model) => this.toEntity(model));
//   }
//
//   public static toModelArray(entities: TransactionEntity[]): Transaction[] {
//     return entities.map((entity) => this.toModel(entity));
//   }
// }
