services:
  mongo_primary:
    image: mongo:8.0.11
    container_name: mongo_primary
    ports:
      - 20211:27017
    command:
      [
        "mongod",
        "--replSet", "rs0",
        "--bind_ip_all"
      ]
    volumes:
      - ./data/mongo_primary:/data/db
      - ./data/mongo_primary_config:/data/configdb
    networks:
      - mongo-network
    restart: unless-stopped

  mongo_secondary:
    image: mongo:8.0.11
    container_name: mongo_secondary
    ports:
      - 20212:27017
    command:
      [
        "mongod",
        "--replSet", "rs0",
        "--bind_ip_all"
      ]
    volumes:
      - ./data/mongo_secondary:/data/db
      - ./data/mongo_secondary_config:/data/configdb
    networks:
      - mongo-network
    restart: unless-stopped

networks:
  mongo-network:
    driver: bridge
