export const SERIALPORT_MODULE_CONFIG = Symbol('SERIALPORT_MODULE_CONFIG');
export const DISCOVERY_CONFIG = Symbol('SERIALPORT_DISCOVERY_CONFIG');
export const MONITORING_CONFIG = Symbol('SERIALPORT_MONITORING_CONFIG');
