// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { AREA_MODEL_TOKEN, Area } from '../schema/area.schema';

@Injectable()
export class AreaMRepository extends BaseRepository<Area> {
  constructor(@InjectModel(AREA_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Area>) {
    super(_model);
  }
}
