// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { BIN_ITEM_MODEL_TOKEN, BinItem } from '../schema/bin-item.schema';

@Injectable()
export class BinItemMRepository extends BaseRepository<BinItem> {
  constructor(@InjectModel(BIN_ITEM_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<BinItem>) {
    super(_model);
  }
}
