// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { BIN_MODEL_TOKEN, Bin } from '../schema/bin.schema';

@Injectable()
export class BinMRepository extends BaseRepository<Bin> {
  constructor(@InjectModel(BIN_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Bin>) {
    super(_model);
  }
}
