// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { CABINET_MODEL_TOKEN, Cabinet } from '../schema/cabinet.schema';

@Injectable()
export class CabinetMRepository extends BaseRepository<Cabinet> {
  constructor(@InjectModel(CABINET_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Cabinet>) {
    super(_model);
  }
}
