// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { CARD_MODEL_TOKEN, Card } from '../schema/card.schema';

@Injectable()
export class CardMRepository extends BaseRepository<Card> {
  constructor(@InjectModel(CARD_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Card>) {
    super(_model);
  }
}
