// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { CONDITION_MODEL_TOKEN, Condition } from '../schema/condition.schema';

@Injectable()
export class ConditionMRepository extends BaseRepository<Condition> {
  constructor(@InjectModel(CONDITION_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Condition>) {
    super(_model);
  }
}
