// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { DEVICE_MODEL_TOKEN, Device } from '../schema/device.schema';

@Injectable()
export class DeviceMRepository extends BaseRepository<Device> {
  constructor(@InjectModel(DEVICE_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Device>) {
    super(_model);
  }
}
