// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { FINGERPRINT_MODEL_TOKEN, Fingerprint } from '../schema/fingerprint.schema';

@Injectable()
export class FingerprintMRepository extends BaseRepository<Fingerprint> {
  constructor(@InjectModel(FINGERPRINT_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Fingerprint>) {
    super(_model);
  }
}
