// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

export * from './area.repository';
export * from './bin-item.repository';
export * from './bin.repository';
export * from './cabinet.repository';
export * from './card.repository';
export * from './condition.repository';
export * from './device.repository';
export * from './fingerprint.repository';
export * from './item-type.repository';
export * from './item.repository';
export * from './job-card.repository';
export * from './log.repository';
export * from './meta-data.repository';
export * from './port.repository';
export * from './return-item.repository';
export * from './site-user.repository';
export * from './site.repository';
export * from './tablet.repository';
export * from './transaction.repository';
export * from './user.repository';
