// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { ITEM_MODEL_TOKEN, Item } from '../schema/item.schema';

@Injectable()
export class ItemMRepository extends BaseRepository<Item> {
  constructor(@InjectModel(ITEM_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Item>) {
    super(_model);
  }
}
