// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { ITEM_TYPE_MODEL_TOKEN, ItemType } from '../schema/item-type.schema';

@Injectable()
export class ItemTypeMRepository extends BaseRepository<ItemType> {
  constructor(@InjectModel(ITEM_TYPE_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<ItemType>) {
    super(_model);
  }
}
