// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { JOB_CARD_MODEL_TOKEN, JobCard } from '../schema/job-card.schema';

@Injectable()
export class JobCardMRepository extends BaseRepository<JobCard> {
  constructor(@InjectModel(JOB_CARD_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<JobCard>) {
    super(_model);
  }
}
