// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { LOG_MODEL_TOKEN, Log } from '../schema/log.schema';

@Injectable()
export class LogMRepository extends BaseRepository<Log> {
  constructor(@InjectModel(LOG_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Log>) {
    super(_model);
  }
}
