// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { META_DATA_MODEL_TOKEN, MetaData } from '../schema/meta-data.schema';

@Injectable()
export class MetaDataMRepository extends BaseRepository<MetaData> {
  constructor(@InjectModel(META_DATA_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<MetaData>) {
    super(_model);
  }
}
