// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { PORT_MODEL_TOKEN, Port } from '../schema/port.schema';

@Injectable()
export class PortMRepository extends BaseRepository<Port> {
  constructor(@InjectModel(PORT_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Port>) {
    super(_model);
  }
}
