// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { RETURN_ITEM_MODEL_TOKEN, ReturnItem } from '../schema/return-item.schema';

@Injectable()
export class ReturnItemMRepository extends BaseRepository<ReturnItem> {
  constructor(@InjectModel(RETURN_ITEM_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<ReturnItem>) {
    super(_model);
  }
}
