// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { SITE_USER_MODEL_TOKEN, SiteUser } from '../schema/site-user.schema';

@Injectable()
export class SiteUserMRepository extends BaseRepository<SiteUser> {
  constructor(@InjectModel(SITE_USER_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<SiteUser>) {
    super(_model);
  }
}
