// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { SITE_MODEL_TOKEN, Site } from '../schema/site.schema';

@Injectable()
export class SiteMRepository extends BaseRepository<Site> {
  constructor(@InjectModel(SITE_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Site>) {
    super(_model);
  }
}
