// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { TABLET_MODEL_TOKEN, Tablet } from '../schema/tablet.schema';

@Injectable()
export class TabletMRepository extends BaseRepository<Tablet> {
  constructor(@InjectModel(TABLET_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Tablet>) {
    super(_model);
  }
}
