// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { TRANSACTION_MODEL_TOKEN, Transaction } from '../schema/transaction.schema';

@Injectable()
export class TransactionMRepository extends BaseRepository<Transaction> {
  constructor(@InjectModel(TRANSACTION_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<Transaction>) {
    super(_model);
  }
}
