// =============================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by: generate-repositories.ts
// =============================================

import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

import { BaseRepository } from '../base.repository';
import { SoftDeleteModel } from '../plugins/soft-delete';
import { USER_MODEL_TOKEN, User } from '../schema/user.schema';

@Injectable()
export class UserMRepository extends BaseRepository<User> {
  constructor(@InjectModel(USER_MODEL_TOKEN) protected readonly _model: SoftDeleteModel<User>) {
    super(_model);
  }
}
