export type ItemDto = {
  id: string;
  siteId: string;
  partNo: string;
  materialNo: string;
  itemTypeId: string;
  name: string;
  supplierEmail: string | null;
  itemAccount: string | null;
  criCode: string | null;
  uom: string | null;
  materialGroup: string | null;
  hasBatchNumber: boolean;
  hasSerialNumber: boolean;
  hasMinChargeTime: boolean;
  hasInspection: boolean;
  hasExpiryDate: boolean;
  hasHydrostaticTest: boolean;
  hasRFID: boolean;
  hasBarcode: boolean;
  description: string | null;
  itemImage: string | null;
  unitCost: number;
  retailCost: number;
  createdBy: string;
  updatedBy: string;
  updatedAt: string;
  createdAt: string;
};
