export enum FINGERPRINT_CMD {
  REGISTER = 1,
  VERIFY = 2,
}

export enum FINGERPRINT_RESPONSE_ID {
  SUCCESS_REGISTER = 1,
  SUCCESS_VERIFY = 2,

  ERROR_CONNECT = 4,
  ERROR_REGISTER = 5,
  ERROR_VERIFY = 6,
}
